# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# https://docs.readthedocs.io/en/stable/config-file/v2.html#formats
formats: "all"

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools: {python: "3.10"}
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - which sphinx-build || true
      - poetry install
      - which sphinx-build
      - poetry run which sphinx-build || true
    pre_build:
      - poetry run sphinx-build -W --keep-going -q -b linkcheck -d _build/doctrees docs/ _build/linkcheck

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
